CREATE DATABASE UsersGroups
GO

USE UsersGroups
GO

CREATE TABLE Groups(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL,
	Description NVARCHAR(MAX)
)
GO

CREATE TABLE Users(
	Id	INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL,
	GroupId INT NOT NULL,
	CONSTRAINT FK_Users_Group FOREIGN KEY(GroupId)
		REFERENCES dbo.Groups(Id)
)
GO

